# Generated by Django 4.2.8 on 2026-03-11 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seller_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("business", "Business"),
                            ("corporate", "Corporate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("intended_item_categories", models.JSONField(default=list)),
                ("phone", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
                ("full_name_or_business_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=120)),
                ("country", models.CharField(default="Nepal", max_length=120)),
                ("payout_details", models.JSONField(blank=True, default=dict)),
                ("submission_notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending review"),
                            ("under_verification", "Under verification"),
                            ("needs_more_documents", "Needs more documents"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending_review",
                        max_length=32,
                    ),
                ),
                ("admin_remarks", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_seller_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seller_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("business", "Business"),
                            ("corporate", "Corporate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=32, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=120, null=True)),
                ("country", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending review"),
                            ("under_verification", "Under verification"),
                            ("needs_more_documents", "Needs more documents"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending_review",
                        max_length=32,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellerApplicationStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending_review", "Pending review"),
                            ("under_verification", "Under verification"),
                            ("needs_more_documents", "Needs more documents"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending review"),
                            ("under_verification", "Under verification"),
                            ("needs_more_documents", "Needs more documents"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        max_length=32,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seller_status_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="sellers.sellerapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("citizenship", "Citizenship"),
                            ("passport", "Passport"),
                            ("selfie", "Selfie / Face verification"),
                            (
                                "business_registration",
                                "Business registration certificate",
                            ),
                            ("company_registration", "Company registration document"),
                            ("pan_vat", "PAN / VAT document"),
                            ("authorization_letter", "Authorization letter"),
                            (
                                "authorized_representative_id",
                                "Authorized representative ID",
                            ),
                            ("vehicle_bluebook", "Vehicle registration / Bluebook"),
                            ("tax_clearance", "Tax clearance"),
                            ("property_ownership", "Ownership certificate"),
                            ("property_legal", "Property legal document"),
                            ("invoice_source_proof", "Invoice / source proof"),
                            ("ownership_proof", "Proof of ownership"),
                            ("authenticity_proof", "Authenticity proof"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="verification_documents/%Y/%m/%d/"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("needs_reupload", "Needs reupload"),
                        ],
                        default="submitted",
                        max_length=32,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="sellers.sellerapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "unique_together": {("application", "document_type", "file")},
            },
        ),
        migrations.AddIndex(
            model_name="sellerapplication",
            index=models.Index(
                fields=["user", "status"], name="sellers_sel_user_id_a5f0dd_idx"
            ),
        ),
    ]
