# Generated by Django 4.2.8 on 2026-03-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_verified_seller_alter_user_role_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SellerRequest",
        ),
    ]
